apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{values.name}}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: {{values.name}} 
  name: {{values.name}}
spec:
  ports:
  - name: app
    port: {{values.appPort}}
    protocol: TCP
    targetPort: {{values.appPort}}
  {%- if values.dbRequired %}
  - name: database
    port: {{values.dbPort}}
    protocol: TCP
    targetPort: {{values.dbPort}}
  {%- endif %}
  selector:
    app.kubernetes.io/instance: {{values.name}} 
